#!/bin/bash
# Quick Test Commands for Signal Project
# Location: /Users/madhuriamam/Idea-Connector/signal/apps/backend/

# Make sure you're in the backend directory first
# cd /Users/madhuriamam/Idea-Connector/signal/apps/backend

echo "🧪 Signal Project Test Suite"
echo "=============================="
echo ""
echo "Available tests:"
echo ""
echo "1. Test Environment Variables:"
echo "   npm run test:env"
echo "   → Checks .env file is loaded with all required config"
echo ""
echo "2. Test Database Connection:"
echo "   npm run test:db"
echo "   → Verifies Node.js can connect to PostgreSQL signal_db"
echo "   → Checks pgvector extension is loaded"
echo "   → Shows database schema"
echo ""
echo "3. Test Dependencies:"
echo "   npm run test:deps"
echo "   → Verifies all 10 core npm packages load correctly"
echo ""
echo "4. Test External APIs:"
echo "   npm run test:apis"
echo "   → Validates OpenAI API key format"
echo "   → Tests Redis/Upstash connectivity"
echo ""
echo "5. Run All Tests:"
echo "   npm run test:all"
echo "   → Runs tests 1-4 in sequence"
echo ""
echo "=============================="
echo ""
echo "What Each Test Tells You:"
echo ""
echo "✅ test:env    → Your secrets are loaded correctly"
echo "✅ test:db     → Your PostgreSQL setup is working"
echo "✅ test:deps   → Your npm packages are installed properly"
echo "✅ test:apis   → Your external services are connected"
echo ""
echo "If all pass → You're ready to build Signal APIs! 🚀"
echo ""
